kind: "BuildConfig"
apiVersion: "build.openshift.io/v1"
metadata:
  name: "simple-pipeline"
spec:
  source:
    contextDir: simple-pipeline
    git:
      uri: "https://github.com/jbbarquero/DO288-apps"
      ref: "jenkins-pipeline"
  strategy:
    jenkinsPipelineStrategy:
      type: JenkinsPipeline
